create table t_picture
(
    id        bigint generated by default as identity
        constraint pk_t_picture
            primary key,
    url       varchar(255),
    title     varchar(255),
    file_name varchar(255),
    content   bytea
);